application:
    image: symfony/code
    volumes:
        - symfony:/var/www/symfony
        - logs/symfony:/var/www/symfony/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laposte_fr
        MYSQL_USER: laposte_fr_user
        MYSQL_PASSWORD: br152qT3
php:
    image: symfony/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    image: symfony/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - logs/nginx/:/var/log/nginx
